import type { Metadata } from "next";
import "./globals.css";
import Script from 'next/script'


export const metadata: Metadata = {
  title: "Vaarin Jain Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
      {/* Google Font */}
      <link
        href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap"
        rel="stylesheet"
      />
    </head>
    <body>
      {/* Load GSAP before your components mount */}
      <Script
        src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.4/gsap.min.js"
        strategy="beforeInteractive"
      />

      {children}
    </body>
  </html>
  );
}
